### ISSUE TITLE
coding to-do 

### ISSUE THREAD

**Issue by sa-lee** [sa-lee/thesis#4]
### app 

- [x] make the app run in the rstudio viewer as a shiny, 
- [x] sort out the stop / play / brush circuit
- [x] modularise the app logic - no need for the simple tour to be separate to the linked version

### brushing semantics

- [ ] allow the user to parameterise the brush, via a brush_spec 
- [ ] re-implement neighbour brush, i think doing this on the js side could be simpler?
- [ ] re-sort data on brush (using `order` encoding), could also be done server side in r

### general vis

- [x] resizing based on size of div, i think this should be possible _solved_ by specifying height and width fill the container
- [ ] allow specifying color palettes  and type etc.
